name: Build and Deploy Demo
permissions:
  contents: write

on:
  push:
    paths:
      - 'demo/**'
      - '.github/workflows/build-demo.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps and build demo
        working-directory: ./demo
        run: |
          npm ci
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo/build
          publish_branch: gh-pages
